name: Bug report
description: Report a reproducible problem.
title: '[Bug]: '
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click...
        3. See error...
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, browser, Node version
